data:
  image_dir: "data/Image"
  mask_dir: "data/Mask"
  augmented_image_dir: "data/augmented_images"
  augmented_mask_dir: "data/augmented_masks"
  shuffle: true

training:
  batch_size: 64
  image_size: [64, 64]
  epochs: 15
  learning_rate: 0.0001
  dropout_rate: 0.1
  use_augment: true

model:
  name: "unet"
